apiVersion: v1
kind: Pod
metadata:
  name: server-2
  labels:
    app: server
spec:
  containers:
    - image: server
      imagePullPolicy: Never
      name: server
      ports:
        - containerPort: 3000
