apiVersion: v1
kind: Pod
metadata:
  name: client-1
  labels:
    app: client
spec:
  containers:
    - image: client
      imagePullPolicy: Never
      name: client
      ports:
        - containerPort: 80
